code --install-extension bradlc.vscode-tailwindcss
code --install-extension bungcip.better-toml
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension dbaeumer.vscode-eslint
code --install-extension esbenp.prettier-vscode
code --install-extension GrapeCity.gc-excelviewer
code --install-extension idleberg.applescript
code --install-extension jock.svg
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension jprestidge.theme-material-theme
code --install-extension karunamurti.haml
code --install-extension Kasik96.swift
code --install-extension mermade.openapi-lint
code --install-extension misogi.ruby-rubocop
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension oderwat.indent-rainbow
code --install-extension PKief.material-icon-theme
code --install-extension rebornix.ruby
code --install-extension redhat.vscode-yaml
code --install-extension selfrefactor.niketa-theme
code --install-extension sensourceinc.vscode-sql-beautify
code --install-extension Shan.code-settings-sync
code --install-extension shinnn.stylelint
code --install-extension silvenon.mdx
code --install-extension spywhere.guides
code --install-extension waderyan.gitblame
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhuangtongfa.Material-theme
