#!/bin/sh
#
# bootstrap installs things.

# Assume everyone's on OS X and run Homebrew (*nix-ers beware)
if [ $(uname -s) = "Darwin" ]
then
  . script/homebrew
  . script/softwares
fi

# Configure osx
. osx/osx

# Run the install (I'd like to pull this out of rake, eventually)
rake install
