#!/bin/sh
#### Applications

brew install caskroom/cask/brew-cask

brew cask install alfred
brew cask install calibre
brew cask install cleanmymac
brew cask install clipmenu
brew cask install disk-inventory-x
brew cask install dropbox
brew cask install f-lux
brew cask install github-desktop
brew cask install growlnotify
brew cask install imageoptim
brew cask install iterm2
brew cask install rescuetime
brew cask install skype
brew cask install slack
brew cask install soleol
brew cask install spectacle
brew cask install spotify
brew cask install transmission
brew cask install vlc

# Unstable

brew tap caskroom/versions
brew cask install sublime-text3
