# Starship prompt https://starship.rs/

add_newline = true

[character]
success_symbol = "[➜](white)"
error_symbol = "[➜](white)"

[aws]
disabled = true

[git_branch]
symbol = ""
format = "[$symbol$branch]($style) "
style = "bold purple"

[git_status]
style = "bold purple"

[package]
disabled = true

[ruby]
symbol = 'ruby'
format = '[$symbol\[($version)\]]($style) '

[nodejs]
symbol = 'node'
format = '[$symbol\[($version)\]]($style) '

[python]
symbol = 'python'
format = '[${symbol}\[${pyenv_prefix}(${version} )(\($virtualenv\) )\]]($style) '
