# Starship prompt https://starship.rs/

add_newline = true

[character]
success_symbol = "[➜](green)"

[aws]
disabled = true

[git_branch]
symbol = ""
format = "[$symbol$branch]($style) "
style = "bold purple"

[git_status]
style = "bold purple"

[ruby]
symbol = 'ruby'
format = '[$symbol\(($version)\)]($style) '

[nodejs]
symbol = 'node'
format = '[$symbol\(($version)\)]($style) '
