format = """
[░▒▓](#769ff0)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$nodejs\
$python\
$ruby\
$nix_shell\
[](fg:#212736)\
$cmd_duration\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…"

[git_branch]
symbol = ""
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[nodejs]
symbol = ""
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[python]
symbol = ""
format = '[[ $symbol ($version)(\($virtualenv\)) ](fg:#769ff0 bg:#212736)]($style)'

[ruby]
symbol = ""
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[nix_shell]
symbol = "󱄅"
format = '[[ $symbol $state:($name) ](fg:#769ff0 bg:#212736)]($style)'

[cmd_duration]
format = ' [ $duration]($style)'
